// Generated by `node scripts/flagship-demo.mjs --write-site`. Do not edit by hand.
// A recorded run of the real ArchMap CLI on the synthetic examples/lending-desk sample.
/* global window */
window.ARCHMAP_DEMO = {
  "schema_version": 1,
  "kind": "archmap-recorded-demo",
  "recorded": true,
  "synthetic": true,
  "archmap_version": "0.0.0",
  "sample": "examples/lending-desk",
  "generator": "node scripts/flagship-demo.mjs --write-site",
  "sanitization": [
    "The disposable copy's absolute path is replaced with <disposable-copy>.",
    "The random project id from init is replaced with proj_<random-at-init>.",
    "Commits use a fixed demo identity and fixed dates, so SHAs are reproducible."
  ],
  "commits": {
    "sample": "185c83fc36b25727c1c0e26a13947fe2d643659f",
    "edit": "5d5c494696d2875394da0a66958718f34de2fbd4"
  },
  "files": [
    {
      "path": "README.md",
      "text": "# lending-desk (synthetic sample)\n\nA deliberately small, invented TypeScript service used to demonstrate ArchMap. It models a\nneighbourhood tool library: members borrow drills and ladders, the desk computes due dates and\nlate fees, and a reminder job posts to a webhook. None of it is production code, and it has no\ndependencies to install.\n\n- `src/loans/policy.ts` — loan length and late-fee rules (the file the demo edits)\n- `src/loans/service.ts` — checkout and return, built on the policy and inventory\n- `src/catalog/inventory.ts` — in-memory tool inventory\n- `src/http/routes.ts` — HTTP handlers registered on a minimal router\n- `src/notify/reminders.ts` — overdue reminders sent with `fetch`\n- `src/plugins/load.ts` — optional extensions loaded by a computed module name\n- `bin/lending-desk.ts` — command-line entry point\n\nSee [docs/architecture.md](docs/architecture.md) for the intended design. ArchMap's demo copies\nthis directory into a fresh temporary Git repository before scanning it; the files here are never\nmodified.\n"
    },
    {
      "path": "bin/lending-desk.ts",
      "text": "#!/usr/bin/env node\n/** Command-line entry point: seeds a demo inventory and prints the routes it would serve. */\n\nimport { Inventory } from '../src/catalog/inventory.js';\nimport { registerRoutes, type Handler } from '../src/http/routes.js';\nimport { LoanService } from '../src/loans/service.js';\nimport { loadPlugins } from '../src/plugins/load.js';\n\nconst inventory = new Inventory();\ninventory.add({ id: 'drill-1', name: 'Cordless drill', available: true });\ninventory.add({ id: 'ladder-1', name: 'Step ladder', available: true });\n\nconst loans = new LoanService(inventory);\nconst routes: string[] = [];\nregisterRoutes(\n  {\n    get: (path: string, _handler: Handler) => routes.push(`GET ${path}`),\n    post: (path: string, _handler: Handler) => routes.push(`POST ${path}`),\n  },\n  inventory,\n  loans,\n);\n\nawait loadPlugins((process.env.LENDING_DESK_PLUGINS ?? '').split(',').filter(Boolean));\nconsole.log(routes.join('\\n'));\n"
    },
    {
      "path": "docs/architecture.md",
      "text": "# lending-desk architecture\n\nThe desk has one rule source: `src/loans/policy.ts`. Every due date and late fee is derived\nfrom it, so a policy change should be reviewed together with the checkout service, the HTTP\nhandlers that expose loans, and the overdue reminder job.\n\n## Flow\n\n1. `bin/lending-desk.ts` wires the inventory, loan service, and router.\n2. `src/http/routes.ts` translates requests into `LoanService` calls.\n3. `src/loans/service.ts` asks the policy for due dates and fees.\n4. `src/notify/reminders.ts` finds overdue loans and posts a reminder to the configured webhook.\n\n## Extension point\n\n`src/plugins/load.ts` imports extensions by a name read from configuration. The module name is\nonly known at runtime.\n"
    },
    {
      "path": "package.json",
      "text": "{\n  \"name\": \"lending-desk\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \"description\": \"Synthetic ArchMap sample: a small tool-library lending service.\",\n  \"type\": \"module\",\n  \"bin\": {\n    \"lending-desk\": \"./bin/lending-desk.ts\"\n  }\n}\n"
    },
    {
      "path": "src/catalog/inventory.ts",
      "text": "/** In-memory inventory of lendable tools. */\n\nexport interface Tool {\n  id: string;\n  name: string;\n  available: boolean;\n}\n\nexport class Inventory {\n  private readonly tools = new Map<string, Tool>();\n\n  add(tool: Tool): void {\n    this.tools.set(tool.id, tool);\n  }\n\n  get(id: string): Tool | undefined {\n    return this.tools.get(id);\n  }\n\n  setAvailable(id: string, available: boolean): void {\n    const tool = this.tools.get(id);\n    if (tool) tool.available = available;\n  }\n\n  list(): Tool[] {\n    return [...this.tools.values()];\n  }\n}\n"
    },
    {
      "path": "src/http/routes.ts",
      "text": "/** HTTP handlers for the lending desk, registered on a minimal router. */\n\nimport type { Inventory } from '../catalog/inventory.js';\nimport type { LoanService } from '../loans/service.js';\n\nexport interface Request {\n  params: Record<string, string>;\n  body: Record<string, string>;\n}\n\nexport type Handler = (req: Request) => { status: number; body: unknown };\n\nexport interface Router {\n  get(path: string, handler: Handler): void;\n  post(path: string, handler: Handler): void;\n}\n\nexport function registerRoutes(router: Router, inventory: Inventory, loans: LoanService): void {\n  router.get('/tools', () => ({ status: 200, body: inventory.list() }));\n\n  router.post('/loans', (req) => {\n    const loan = loans.checkout(req.body.toolId ?? '', req.body.memberId ?? '', new Date());\n    return { status: 201, body: loan };\n  });\n\n  router.post('/returns/:toolId', (req) => {\n    const loan = loans.giveBack(req.params.toolId ?? '', new Date());\n    return { status: 200, body: loan };\n  });\n}\n"
    },
    {
      "path": "src/loans/policy.ts",
      "text": "/** Loan length and late-fee rules for the tool library. */\n\nexport const LOAN_DAYS = 14;\nexport const DAILY_LATE_FEE_CENTS = 50;\nexport const MAX_LATE_FEE_CENTS = 2000;\n\nconst DAY_MS = 24 * 60 * 60 * 1000;\n\nexport function dueDate(borrowedAt: Date): Date {\n  return new Date(borrowedAt.getTime() + LOAN_DAYS * DAY_MS);\n}\n\nexport function lateFeeCents(due: Date, returnedAt: Date): number {\n  const daysLate = Math.ceil((returnedAt.getTime() - due.getTime()) / DAY_MS);\n  if (daysLate <= 0) return 0;\n  return Math.min(daysLate * DAILY_LATE_FEE_CENTS, MAX_LATE_FEE_CENTS);\n}\n"
    },
    {
      "path": "src/loans/service.ts",
      "text": "/** Checkout and return, built on the loan policy and the inventory. */\n\nimport type { Inventory } from '../catalog/inventory.js';\nimport { dueDate, lateFeeCents } from './policy.js';\n\nexport interface Loan {\n  toolId: string;\n  memberId: string;\n  borrowedAt: Date;\n  due: Date;\n  returnedAt?: Date;\n  feeCents?: number;\n}\n\nexport class LoanService {\n  private readonly loans: Loan[] = [];\n\n  constructor(private readonly inventory: Inventory) {}\n\n  checkout(toolId: string, memberId: string, now: Date): Loan {\n    const tool = this.inventory.get(toolId);\n    if (!tool || !tool.available) throw new Error(`tool ${toolId} is not available`);\n    this.inventory.setAvailable(toolId, false);\n    const loan: Loan = { toolId, memberId, borrowedAt: now, due: dueDate(now) };\n    this.loans.push(loan);\n    return loan;\n  }\n\n  giveBack(toolId: string, now: Date): Loan {\n    const loan = this.loans.find((l) => l.toolId === toolId && !l.returnedAt);\n    if (!loan) throw new Error(`tool ${toolId} is not on loan`);\n    loan.returnedAt = now;\n    loan.feeCents = lateFeeCents(loan.due, now);\n    this.inventory.setAvailable(toolId, true);\n    return loan;\n  }\n\n  overdue(now: Date): Loan[] {\n    return this.loans.filter((l) => !l.returnedAt && l.due.getTime() < now.getTime());\n  }\n}\n"
    },
    {
      "path": "src/notify/reminders.ts",
      "text": "/** Overdue reminders, posted as JSON to a configured webhook. */\n\nimport type { LoanService } from '../loans/service.js';\n\nexport async function sendOverdueReminders(\n  loans: LoanService,\n  webhookUrl: string,\n  now: Date,\n): Promise<number> {\n  const overdue = loans.overdue(now);\n  for (const loan of overdue) {\n    await fetch(webhookUrl, {\n      method: 'POST',\n      headers: { 'content-type': 'application/json' },\n      body: JSON.stringify({ memberId: loan.memberId, toolId: loan.toolId, due: loan.due }),\n    });\n  }\n  return overdue.length;\n}\n"
    },
    {
      "path": "src/plugins/load.ts",
      "text": "/** Optional desk extensions, loaded by a module name that is only known at runtime. */\n\nexport interface DeskPlugin {\n  name: string;\n  start(): void;\n}\n\nexport async function loadPlugins(names: string[]): Promise<DeskPlugin[]> {\n  const plugins: DeskPlugin[] = [];\n  for (const name of names) {\n    const mod = (await import(`./${name}.js`)) as { default: DeskPlugin };\n    plugins.push(mod.default);\n  }\n  return plugins;\n}\n"
    },
    {
      "path": "tsconfig.json",
      "text": "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"NodeNext\",\n    \"moduleResolution\": \"NodeNext\",\n    \"lib\": [\"ES2022\", \"DOM\"],\n    \"strict\": true,\n    \"noEmit\": true,\n    \"skipLibCheck\": true\n  },\n  \"include\": [\"src\", \"bin\"]\n}\n"
    }
  ],
  "steps": [
    {
      "id": "init",
      "title": "Initialize",
      "command": "archmap init --json",
      "exit_code": 0,
      "note": "Creates .archmap/project.yaml at the Git top level of the working directory.",
      "output": {
        "schema_version": 1,
        "command": "init",
        "initialized": true,
        "root": "<disposable-copy>",
        "project": {
          "id": "proj_<random-at-init>",
          "name": "lending-desk"
        }
      }
    },
    {
      "id": "scan",
      "title": "Scan",
      "command": "archmap scan --json",
      "exit_code": 0,
      "note": "Deterministic analyzers write reviewable YAML: a snapshot plus one file per node.",
      "output": {
        "schema_version": 1,
        "command": "scan",
        "wrote": true,
        "changed": true,
        "base_commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
        "dirty": false,
        "files": 11,
        "nodes": 22,
        "excluded": {
          "excluded-dir": 0,
          "secret": 0,
          "too-large": 0,
          "binary": 0,
          "symlink": 0
        }
      }
    },
    {
      "id": "status-clean",
      "title": "Status",
      "command": "archmap status --json",
      "exit_code": 0,
      "note": "The working tree matches the snapshot, so nothing is stale.",
      "output": {
        "schema_version": 1,
        "command": "status",
        "scanned": true,
        "clean": true,
        "base_commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
        "dirty": false,
        "diff": {
          "added": [],
          "modified": [],
          "deleted": [],
          "renamed": [],
          "unchanged": 11
        },
        "drift": [],
        "stale_nodes": [],
        "file_count": 11,
        "node_count": 22
      }
    },
    {
      "id": "context",
      "title": "Context",
      "command": "archmap context src/loans/policy.ts --json",
      "exit_code": 0,
      "note": "The smallest evidence-backed context for a file, within an estimated token budget.",
      "output": {
        "schema_version": 1,
        "command": "context",
        "budget": 2000,
        "used_tokens": 485,
        "requested_paths": [
          "src/loans/policy.ts"
        ],
        "included": [
          {
            "reason": "target: the requested file",
            "tokens": 68,
            "node": {
              "claims": [],
              "id": "node_4e8343b6e8d4b5ae",
              "kind": "module",
              "relations": [],
              "scope": {
                "files": [
                  "src/loans/policy.ts"
                ],
                "symbols": [
                  "DAILY_LATE_FEE_CENTS",
                  "LOAN_DAYS",
                  "MAX_LATE_FEE_CENTS",
                  "dueDate",
                  "lateFeeCents"
                ]
              },
              "slug": "src-loans-policy-ts",
              "title": "src/loans/policy.ts"
            }
          },
          {
            "reason": "imports the requested file",
            "tokens": 332,
            "node": {
              "claims": [],
              "id": "node_3c3db08946e0fc82",
              "kind": "module",
              "relations": [
                {
                  "certainty": "known",
                  "evidence": [
                    {
                      "analyzer": "typescript",
                      "analyzer_version": "0.1.0",
                      "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                      "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                      "extract_hash": "sha256:13df485db4ae70e91ea559576ef592cdafbabdfc0a7bd96be9106dd5addfccaf",
                      "path": "src/loans/service.ts",
                      "repository": "local",
                      "symbol": "./policy.js"
                    }
                  ],
                  "id": "rel_76361d99c9df6a71",
                  "provenance": {
                    "actor": "analyzer",
                    "created_at": "1970-01-01T00:00:00Z"
                  },
                  "target": "node_4e8343b6e8d4b5ae",
                  "type": "imports"
                },
                {
                  "certainty": "known",
                  "evidence": [
                    {
                      "analyzer": "typescript",
                      "analyzer_version": "0.1.0",
                      "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                      "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                      "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
                      "path": "src/loans/service.ts",
                      "repository": "local",
                      "symbol": "../catalog/inventory.js"
                    }
                  ],
                  "id": "rel_ad3c99b585cd8dab",
                  "provenance": {
                    "actor": "analyzer",
                    "created_at": "1970-01-01T00:00:00Z"
                  },
                  "target": "node_7ff22e071e772116",
                  "type": "imports"
                }
              ],
              "scope": {
                "files": [
                  "src/loans/service.ts"
                ],
                "symbols": [
                  "Loan",
                  "LoanService"
                ]
              },
              "slug": "src-loans-service-ts",
              "title": "src/loans/service.ts"
            }
          },
          {
            "reason": "parent view: contains the requested file",
            "tokens": 42,
            "node": {
              "claims": [],
              "id": "node_b637661b273ec066",
              "kind": "module",
              "relations": [],
              "scope": {
                "files": [
                  "src/loans/policy.ts",
                  "src/loans/service.ts"
                ]
              },
              "slug": "src-loans",
              "title": "src/loans"
            }
          },
          {
            "reason": "parent view: repository root",
            "tokens": 43,
            "node": {
              "claims": [],
              "id": "node_cdb4ee2aea69cc6a",
              "kind": "system",
              "relations": [],
              "scope": {
                "files": [
                  "README.md",
                  "package.json",
                  "tsconfig.json"
                ]
              },
              "slug": "repository",
              "title": "lending-desk"
            }
          }
        ],
        "omitted": []
      }
    },
    {
      "id": "impact",
      "title": "Impact",
      "command": "archmap impact src/loans/policy.ts --json",
      "exit_code": 0,
      "note": "Everything that scopes or transitively imports the file.",
      "output": {
        "schema_version": 1,
        "command": "impact",
        "requested_paths": [
          "src/loans/policy.ts"
        ],
        "seeds": [
          "node_4e8343b6e8d4b5ae",
          "node_b637661b273ec066"
        ],
        "impacted": [
          {
            "id": "node_0be2e45fa1ec51de",
            "kind": "module",
            "title": "src/notify/reminders.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_1a10a4363300c177",
            "kind": "module",
            "title": "bin/lending-desk.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_3c3db08946e0fc82",
            "kind": "module",
            "title": "src/loans/service.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_4e8343b6e8d4b5ae",
            "kind": "module",
            "title": "src/loans/policy.ts",
            "reason": "directly scopes a changed file"
          },
          {
            "id": "node_8ec0bdcd9405afe9",
            "kind": "module",
            "title": "src/http/routes.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_b637661b273ec066",
            "kind": "module",
            "title": "src/loans",
            "reason": "directly scopes a changed file"
          },
          {
            "id": "node_cdb4ee2aea69cc6a",
            "kind": "system",
            "title": "lending-desk",
            "reason": "parent view: repository root"
          }
        ]
      }
    },
    {
      "id": "evidence",
      "title": "Evidence",
      "command": "archmap evidence node_3c3db08946e0fc82 --json",
      "exit_code": 0,
      "note": "Source pointers for the service module: path, symbol, blob hash, commit, analyzer.",
      "output": {
        "schema_version": 1,
        "command": "evidence",
        "target": "node_3c3db08946e0fc82",
        "found": true,
        "matched": "node",
        "evidence": [
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:13df485db4ae70e91ea559576ef592cdafbabdfc0a7bd96be9106dd5addfccaf",
            "path": "src/loans/service.ts",
            "repository": "local",
            "symbol": "./policy.js"
          },
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
            "path": "src/loans/service.ts",
            "repository": "local",
            "symbol": "../catalog/inventory.js"
          }
        ]
      }
    },
    {
      "id": "evidence-partial",
      "title": "Partial evidence",
      "command": "archmap evidence node_8ec0bdcd9405afe9 --json",
      "exit_code": 0,
      "note": "Route registrations are heuristic, so their relations are recorded as partial.",
      "output": {
        "schema_version": 1,
        "command": "evidence",
        "target": "node_8ec0bdcd9405afe9",
        "found": true,
        "matched": "node",
        "evidence": [
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:0bfdfadcef0e0ec70dbf47f46c6a745086fa7f0884d84d7ff6d84bb73bfcfe48",
            "path": "src/http/routes.ts",
            "repository": "local"
          },
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:a64a3af68a3ae9926348ca206ee3da5234c31f06e8104987d15705e89236db74",
            "path": "src/http/routes.ts",
            "repository": "local"
          },
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:958fc93c6c592ad372eb9e6181f1220868b8216e948718de5b5a6eb3da148713",
            "path": "src/http/routes.ts",
            "repository": "local"
          },
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
            "path": "src/http/routes.ts",
            "repository": "local",
            "symbol": "../catalog/inventory.js"
          },
          {
            "analyzer": "typescript",
            "analyzer_version": "0.1.0",
            "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
            "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
            "extract_hash": "sha256:0034c2f58f5dd5870a3b3b9de595cdd91283eed65ec3f752658db48a97c9f73e",
            "path": "src/http/routes.ts",
            "repository": "local",
            "symbol": "../loans/service.js"
          }
        ]
      }
    },
    {
      "id": "edit",
      "title": "Edit source",
      "command": "edit src/loans/policy.ts",
      "exit_code": 0,
      "note": "Extend the loan period from 14 to 21 days.",
      "output": {
        "path": "src/loans/policy.ts",
        "before": "export const LOAN_DAYS = 14;",
        "after": "export const LOAN_DAYS = 21;"
      }
    },
    {
      "id": "status-stale",
      "title": "Status after edit",
      "command": "archmap status --json",
      "exit_code": 1,
      "note": "The snapshot no longer matches: the edited file and the nodes that scope it are stale.",
      "output": {
        "schema_version": 1,
        "command": "status",
        "scanned": true,
        "clean": false,
        "base_commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
        "dirty": false,
        "diff": {
          "added": [],
          "modified": [
            "src/loans/policy.ts"
          ],
          "deleted": [],
          "renamed": [],
          "unchanged": 10
        },
        "drift": [
          "snapshot-metadata",
          "node-structure"
        ],
        "stale_nodes": [
          "node_4e8343b6e8d4b5ae",
          "node_b637661b273ec066",
          "node_cdb4ee2aea69cc6a"
        ],
        "file_count": 11,
        "node_count": 22
      }
    },
    {
      "id": "impact-base",
      "title": "Impact from Git",
      "command": "archmap impact --base HEAD --json",
      "exit_code": 0,
      "note": "The changed-file set can also come from git diff.",
      "output": {
        "schema_version": 1,
        "command": "impact",
        "requested_paths": [
          "src/loans/policy.ts"
        ],
        "seeds": [
          "node_4e8343b6e8d4b5ae",
          "node_b637661b273ec066"
        ],
        "impacted": [
          {
            "id": "node_0be2e45fa1ec51de",
            "kind": "module",
            "title": "src/notify/reminders.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_1a10a4363300c177",
            "kind": "module",
            "title": "bin/lending-desk.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_3c3db08946e0fc82",
            "kind": "module",
            "title": "src/loans/service.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_4e8343b6e8d4b5ae",
            "kind": "module",
            "title": "src/loans/policy.ts",
            "reason": "directly scopes a changed file"
          },
          {
            "id": "node_8ec0bdcd9405afe9",
            "kind": "module",
            "title": "src/http/routes.ts",
            "reason": "transitively imports a changed file"
          },
          {
            "id": "node_b637661b273ec066",
            "kind": "module",
            "title": "src/loans",
            "reason": "directly scopes a changed file"
          },
          {
            "id": "node_cdb4ee2aea69cc6a",
            "kind": "system",
            "title": "lending-desk",
            "reason": "parent view: repository root"
          }
        ]
      }
    },
    {
      "id": "commit",
      "title": "Commit edit",
      "command": "git commit -am \"Extend loan period to 21 days\"",
      "exit_code": 0,
      "note": "The source change is committed; the map is now behind HEAD.",
      "output": {
        "commit": "5d5c494696d2875394da0a66958718f34de2fbd4"
      }
    },
    {
      "id": "rescan",
      "title": "Rescan",
      "command": "archmap scan --json",
      "exit_code": 0,
      "note": "Rescanning refreshes the snapshot and the affected nodes.",
      "output": {
        "schema_version": 1,
        "command": "scan",
        "wrote": true,
        "changed": true,
        "base_commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
        "dirty": false,
        "files": 11,
        "nodes": 22,
        "excluded": {
          "excluded-dir": 0,
          "secret": 0,
          "too-large": 0,
          "binary": 0,
          "symlink": 0
        }
      }
    },
    {
      "id": "status-fresh",
      "title": "Status after rescan",
      "command": "archmap status --json",
      "exit_code": 0,
      "note": "Clean again at the new commit.",
      "output": {
        "schema_version": 1,
        "command": "status",
        "scanned": true,
        "clean": true,
        "base_commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
        "dirty": false,
        "diff": {
          "added": [],
          "modified": [],
          "deleted": [],
          "renamed": [],
          "unchanged": 11
        },
        "drift": [],
        "stale_nodes": [],
        "file_count": 11,
        "node_count": 22
      }
    }
  ],
  "graph": {
    "before": [
      {
        "claims": [],
        "id": "node_0be2e45fa1ec51de",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:8d6eacf9eac21c7b640649388f2841fcb1aee78756d60b6209743310b2f3c13e",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:0034c2f58f5dd5870a3b3b9de595cdd91283eed65ec3f752658db48a97c9f73e",
                "path": "src/notify/reminders.ts",
                "repository": "local",
                "symbol": "../loans/service.js"
              }
            ],
            "id": "rel_3dd22ca1557515e6",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:8d6eacf9eac21c7b640649388f2841fcb1aee78756d60b6209743310b2f3c13e",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:70f6ecde3850d2e9a20a3aebd9c777333fcbf946939a3625a5fbde1663620a17",
                "path": "src/notify/reminders.ts",
                "repository": "local"
              }
            ],
            "id": "rel_4f148bb8e609368f",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c177ba986655ed18",
            "type": "calls"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/notify/reminders.ts"
          ],
          "symbols": [
            "sendOverdueReminders"
          ]
        },
        "slug": "src-notify-reminders-ts",
        "title": "src/notify/reminders.ts"
      },
      {
        "claims": [
          {
            "confidence": 1,
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:ed25b2f8ba8274386cc4b7e8fc2e8aa366fc5eb39774d12dec74b50f65fed994",
                "path": "bin/lending-desk.ts",
                "repository": "local"
              }
            ],
            "id": "claim_e6437bb93c7705fc",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "status": "active",
            "text": "Entry point (shebang).",
            "type": "fact"
          }
        ],
        "id": "node_1a10a4363300c177",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:e3937dab3eb274654a23e683b6df0ede76915bcbd62ce37beba980b83fea9736",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/http/routes.js"
              }
            ],
            "id": "rel_60994466f0848455",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_8ec0bdcd9405afe9",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:5887ee7f0c8a5d5228850b813e2ce0623c31fb0b078d0d56765c330c2e0eeed3",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/catalog/inventory.js"
              }
            ],
            "id": "rel_675798d014b0bf8e",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:0c9618426307c2594de3a3eb104b8fdb04e2588ad36ad116dbd8fb398254208c",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/loans/service.js"
              }
            ],
            "id": "rel_8c42b764b6f720fa",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:fbecd63c3c893c71d6c60b263c3ce3ed8b24d26462f00788ab7b89241f3d8493",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/plugins/load.js"
              }
            ],
            "id": "rel_93ac5425b7a5cb06",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c2848c3c55e77a36",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "bin/lending-desk.ts"
          ]
        },
        "slug": "bin-lending-desk-ts",
        "title": "bin/lending-desk.ts"
      },
      {
        "claims": [],
        "id": "node_2264e626255c809c",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/http/routes.ts"
          ]
        },
        "slug": "src-http",
        "title": "src/http"
      },
      {
        "claims": [],
        "id": "node_3c3db08946e0fc82",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:13df485db4ae70e91ea559576ef592cdafbabdfc0a7bd96be9106dd5addfccaf",
                "path": "src/loans/service.ts",
                "repository": "local",
                "symbol": "./policy.js"
              }
            ],
            "id": "rel_76361d99c9df6a71",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_4e8343b6e8d4b5ae",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
                "path": "src/loans/service.ts",
                "repository": "local",
                "symbol": "../catalog/inventory.js"
              }
            ],
            "id": "rel_ad3c99b585cd8dab",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/service.ts"
          ],
          "symbols": [
            "Loan",
            "LoanService"
          ]
        },
        "slug": "src-loans-service-ts",
        "title": "src/loans/service.ts"
      },
      {
        "claims": [],
        "id": "node_43a8f10313ecc5b3",
        "kind": "store",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "markdown",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:c3d9fa24c534de320ae4147844a3f22d85a1a0705a044503974d079d5f007650",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:aa9973bd907d0669f2ebb3a4f1d2bf77fd2cf91c9f76d727fead94f0753eeb51",
                "path": "README.md",
                "repository": "local",
                "symbol": "docs/architecture.md"
              }
            ],
            "id": "rel_4502fb2665d9c11d",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_b06275f4bbc561cd",
            "type": "depends-on"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "README.md"
          ]
        },
        "slug": "readme-md",
        "title": "lending-desk (synthetic sample)"
      },
      {
        "claims": [],
        "id": "node_464a59e385f6961d",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-post-loans",
        "title": "route:POST /loans"
      },
      {
        "claims": [],
        "id": "node_46b42b4229cd7a39",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "docs/architecture.md"
          ]
        },
        "slug": "docs",
        "title": "docs"
      },
      {
        "claims": [],
        "id": "node_4e8343b6e8d4b5ae",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/policy.ts"
          ],
          "symbols": [
            "DAILY_LATE_FEE_CENTS",
            "LOAN_DAYS",
            "MAX_LATE_FEE_CENTS",
            "dueDate",
            "lateFeeCents"
          ]
        },
        "slug": "src-loans-policy-ts",
        "title": "src/loans/policy.ts"
      },
      {
        "claims": [],
        "id": "node_511251a657fd24f0",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-get-tools",
        "title": "route:GET /tools"
      },
      {
        "claims": [],
        "id": "node_51a1f05af85e342e",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "bin/lending-desk.ts"
          ]
        },
        "slug": "bin",
        "title": "bin"
      },
      {
        "claims": [],
        "id": "node_7ff22e071e772116",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/catalog/inventory.ts"
          ],
          "symbols": [
            "Inventory",
            "Tool"
          ]
        },
        "slug": "src-catalog-inventory-ts",
        "title": "src/catalog/inventory.ts"
      },
      {
        "claims": [],
        "id": "node_8ec0bdcd9405afe9",
        "kind": "module",
        "relations": [
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:0bfdfadcef0e0ec70dbf47f46c6a745086fa7f0884d84d7ff6d84bb73bfcfe48",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_213d12b4c2be0dcd",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_464a59e385f6961d",
            "type": "publishes"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:a64a3af68a3ae9926348ca206ee3da5234c31f06e8104987d15705e89236db74",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_86e2737940a9ca71",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_511251a657fd24f0",
            "type": "publishes"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:958fc93c6c592ad372eb9e6181f1220868b8216e948718de5b5a6eb3da148713",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_a8b4b20932d55309",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c263a120d53094fe",
            "type": "publishes"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
                "path": "src/http/routes.ts",
                "repository": "local",
                "symbol": "../catalog/inventory.js"
              }
            ],
            "id": "rel_cf69c49b403b2aaa",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:0034c2f58f5dd5870a3b3b9de595cdd91283eed65ec3f752658db48a97c9f73e",
                "path": "src/http/routes.ts",
                "repository": "local",
                "symbol": "../loans/service.js"
              }
            ],
            "id": "rel_cfc82808345c325f",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/http/routes.ts"
          ],
          "symbols": [
            "Handler",
            "Request",
            "Router",
            "registerRoutes"
          ]
        },
        "slug": "src-http-routes-ts",
        "title": "src/http/routes.ts"
      },
      {
        "claims": [],
        "id": "node_9ea79ac20c37b2a7",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/plugins/load.ts"
          ]
        },
        "slug": "src-plugins",
        "title": "src/plugins"
      },
      {
        "claims": [],
        "id": "node_b06275f4bbc561cd",
        "kind": "store",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "docs/architecture.md"
          ],
          "symbols": [
            "Extension point",
            "Flow"
          ]
        },
        "slug": "docs-architecture-md",
        "title": "lending-desk architecture"
      },
      {
        "claims": [],
        "id": "node_b637661b273ec066",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/policy.ts",
            "src/loans/service.ts"
          ]
        },
        "slug": "src-loans",
        "title": "src/loans"
      },
      {
        "claims": [],
        "id": "node_c177ba986655ed18",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "http-fetch",
        "title": "http:fetch"
      },
      {
        "claims": [],
        "id": "node_c263a120d53094fe",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-post-returns-toolid",
        "title": "route:POST /returns/:toolId"
      },
      {
        "claims": [],
        "id": "node_c2848c3c55e77a36",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/plugins/load.ts"
          ],
          "symbols": [
            "DeskPlugin",
            "loadPlugins"
          ]
        },
        "slug": "src-plugins-load-ts",
        "title": "src/plugins/load.ts"
      },
      {
        "claims": [],
        "id": "node_cdb4ee2aea69cc6a",
        "kind": "system",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "README.md",
            "package.json",
            "tsconfig.json"
          ]
        },
        "slug": "repository",
        "title": "lending-desk"
      },
      {
        "claims": [],
        "id": "node_db5e0f14edd7dda6",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/notify/reminders.ts"
          ]
        },
        "slug": "src-notify",
        "title": "src/notify"
      },
      {
        "claims": [],
        "id": "node_dd54919d93b38f7b",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/catalog/inventory.ts"
          ]
        },
        "slug": "src-catalog",
        "title": "src/catalog"
      },
      {
        "claims": [
          {
            "confidence": 1,
            "evidence": [
              {
                "analyzer": "data",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:2aeebecb58cfa527716fd3d3c17998e68167a606d76df8c4866c3ee04e8c0791",
                "commit": "185c83fc36b25727c1c0e26a13947fe2d643659f",
                "extract_hash": "sha256:b373c2c9eb935662c469cb6eb3e2ff4116e98c1fef2b2fe39ef16bdb71b0ec82",
                "path": "tsconfig.json",
                "repository": "local"
              }
            ],
            "id": "claim_185759f8abb5fab9",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "status": "active",
            "text": "Top-level keys (sorted, max 20): compilerOptions, include.",
            "type": "fact"
          }
        ],
        "id": "node_dde380120d7ca961",
        "kind": "store",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "tsconfig.json"
          ]
        },
        "slug": "tsconfig-json",
        "title": "tsconfig.json"
      }
    ],
    "after": [
      {
        "claims": [],
        "id": "node_0be2e45fa1ec51de",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:8d6eacf9eac21c7b640649388f2841fcb1aee78756d60b6209743310b2f3c13e",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:0034c2f58f5dd5870a3b3b9de595cdd91283eed65ec3f752658db48a97c9f73e",
                "path": "src/notify/reminders.ts",
                "repository": "local",
                "symbol": "../loans/service.js"
              }
            ],
            "id": "rel_3dd22ca1557515e6",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:8d6eacf9eac21c7b640649388f2841fcb1aee78756d60b6209743310b2f3c13e",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:70f6ecde3850d2e9a20a3aebd9c777333fcbf946939a3625a5fbde1663620a17",
                "path": "src/notify/reminders.ts",
                "repository": "local"
              }
            ],
            "id": "rel_4f148bb8e609368f",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c177ba986655ed18",
            "type": "calls"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/notify/reminders.ts"
          ],
          "symbols": [
            "sendOverdueReminders"
          ]
        },
        "slug": "src-notify-reminders-ts",
        "title": "src/notify/reminders.ts"
      },
      {
        "claims": [
          {
            "confidence": 1,
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:ed25b2f8ba8274386cc4b7e8fc2e8aa366fc5eb39774d12dec74b50f65fed994",
                "path": "bin/lending-desk.ts",
                "repository": "local"
              }
            ],
            "id": "claim_e6437bb93c7705fc",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "status": "active",
            "text": "Entry point (shebang).",
            "type": "fact"
          }
        ],
        "id": "node_1a10a4363300c177",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:e3937dab3eb274654a23e683b6df0ede76915bcbd62ce37beba980b83fea9736",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/http/routes.js"
              }
            ],
            "id": "rel_60994466f0848455",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_8ec0bdcd9405afe9",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:5887ee7f0c8a5d5228850b813e2ce0623c31fb0b078d0d56765c330c2e0eeed3",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/catalog/inventory.js"
              }
            ],
            "id": "rel_675798d014b0bf8e",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:0c9618426307c2594de3a3eb104b8fdb04e2588ad36ad116dbd8fb398254208c",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/loans/service.js"
              }
            ],
            "id": "rel_8c42b764b6f720fa",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:1dbd05ffc1317a1b7e2740ea8395bbc8f5ae0850d888ee2135c0c29ebce194e3",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:fbecd63c3c893c71d6c60b263c3ce3ed8b24d26462f00788ab7b89241f3d8493",
                "path": "bin/lending-desk.ts",
                "repository": "local",
                "symbol": "../src/plugins/load.js"
              }
            ],
            "id": "rel_93ac5425b7a5cb06",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c2848c3c55e77a36",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "bin/lending-desk.ts"
          ]
        },
        "slug": "bin-lending-desk-ts",
        "title": "bin/lending-desk.ts"
      },
      {
        "claims": [],
        "id": "node_2264e626255c809c",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/http/routes.ts"
          ]
        },
        "slug": "src-http",
        "title": "src/http"
      },
      {
        "claims": [],
        "id": "node_3c3db08946e0fc82",
        "kind": "module",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:13df485db4ae70e91ea559576ef592cdafbabdfc0a7bd96be9106dd5addfccaf",
                "path": "src/loans/service.ts",
                "repository": "local",
                "symbol": "./policy.js"
              }
            ],
            "id": "rel_76361d99c9df6a71",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_4e8343b6e8d4b5ae",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:fe15bfef5486627991056f1b2fd8fbfbc6efa56877b8041ad4d0a24835e58f7b",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
                "path": "src/loans/service.ts",
                "repository": "local",
                "symbol": "../catalog/inventory.js"
              }
            ],
            "id": "rel_ad3c99b585cd8dab",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/service.ts"
          ],
          "symbols": [
            "Loan",
            "LoanService"
          ]
        },
        "slug": "src-loans-service-ts",
        "title": "src/loans/service.ts"
      },
      {
        "claims": [],
        "id": "node_43a8f10313ecc5b3",
        "kind": "store",
        "relations": [
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "markdown",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:c3d9fa24c534de320ae4147844a3f22d85a1a0705a044503974d079d5f007650",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:aa9973bd907d0669f2ebb3a4f1d2bf77fd2cf91c9f76d727fead94f0753eeb51",
                "path": "README.md",
                "repository": "local",
                "symbol": "docs/architecture.md"
              }
            ],
            "id": "rel_4502fb2665d9c11d",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_b06275f4bbc561cd",
            "type": "depends-on"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "README.md"
          ]
        },
        "slug": "readme-md",
        "title": "lending-desk (synthetic sample)"
      },
      {
        "claims": [],
        "id": "node_464a59e385f6961d",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-post-loans",
        "title": "route:POST /loans"
      },
      {
        "claims": [],
        "id": "node_46b42b4229cd7a39",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "docs/architecture.md"
          ]
        },
        "slug": "docs",
        "title": "docs"
      },
      {
        "claims": [],
        "id": "node_4e8343b6e8d4b5ae",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/policy.ts"
          ],
          "symbols": [
            "DAILY_LATE_FEE_CENTS",
            "LOAN_DAYS",
            "MAX_LATE_FEE_CENTS",
            "dueDate",
            "lateFeeCents"
          ]
        },
        "slug": "src-loans-policy-ts",
        "title": "src/loans/policy.ts"
      },
      {
        "claims": [],
        "id": "node_511251a657fd24f0",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-get-tools",
        "title": "route:GET /tools"
      },
      {
        "claims": [],
        "id": "node_51a1f05af85e342e",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "bin/lending-desk.ts"
          ]
        },
        "slug": "bin",
        "title": "bin"
      },
      {
        "claims": [],
        "id": "node_7ff22e071e772116",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/catalog/inventory.ts"
          ],
          "symbols": [
            "Inventory",
            "Tool"
          ]
        },
        "slug": "src-catalog-inventory-ts",
        "title": "src/catalog/inventory.ts"
      },
      {
        "claims": [],
        "id": "node_8ec0bdcd9405afe9",
        "kind": "module",
        "relations": [
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:0bfdfadcef0e0ec70dbf47f46c6a745086fa7f0884d84d7ff6d84bb73bfcfe48",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_213d12b4c2be0dcd",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_464a59e385f6961d",
            "type": "publishes"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:a64a3af68a3ae9926348ca206ee3da5234c31f06e8104987d15705e89236db74",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_86e2737940a9ca71",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_511251a657fd24f0",
            "type": "publishes"
          },
          {
            "certainty": "partial",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:958fc93c6c592ad372eb9e6181f1220868b8216e948718de5b5a6eb3da148713",
                "path": "src/http/routes.ts",
                "repository": "local"
              }
            ],
            "id": "rel_a8b4b20932d55309",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_c263a120d53094fe",
            "type": "publishes"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:b40defbd9a3789628234a280a81ccbf349345de179d7de9a56f2a5ae86b91a22",
                "path": "src/http/routes.ts",
                "repository": "local",
                "symbol": "../catalog/inventory.js"
              }
            ],
            "id": "rel_cf69c49b403b2aaa",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_7ff22e071e772116",
            "type": "imports"
          },
          {
            "certainty": "known",
            "evidence": [
              {
                "analyzer": "typescript",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:4f5ddea6558fc0495421cb2d0b3f89359a3d6d555c44fda8a3ed74ef071fa833",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:0034c2f58f5dd5870a3b3b9de595cdd91283eed65ec3f752658db48a97c9f73e",
                "path": "src/http/routes.ts",
                "repository": "local",
                "symbol": "../loans/service.js"
              }
            ],
            "id": "rel_cfc82808345c325f",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "target": "node_3c3db08946e0fc82",
            "type": "imports"
          }
        ],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/http/routes.ts"
          ],
          "symbols": [
            "Handler",
            "Request",
            "Router",
            "registerRoutes"
          ]
        },
        "slug": "src-http-routes-ts",
        "title": "src/http/routes.ts"
      },
      {
        "claims": [],
        "id": "node_9ea79ac20c37b2a7",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/plugins/load.ts"
          ]
        },
        "slug": "src-plugins",
        "title": "src/plugins"
      },
      {
        "claims": [],
        "id": "node_b06275f4bbc561cd",
        "kind": "store",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "docs/architecture.md"
          ],
          "symbols": [
            "Extension point",
            "Flow"
          ]
        },
        "slug": "docs-architecture-md",
        "title": "lending-desk architecture"
      },
      {
        "claims": [],
        "id": "node_b637661b273ec066",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/loans/policy.ts",
            "src/loans/service.ts"
          ]
        },
        "slug": "src-loans",
        "title": "src/loans"
      },
      {
        "claims": [],
        "id": "node_c177ba986655ed18",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "http-fetch",
        "title": "http:fetch"
      },
      {
        "claims": [],
        "id": "node_c263a120d53094fe",
        "kind": "external",
        "relations": [],
        "schema_version": 1,
        "slug": "route-post-returns-toolid",
        "title": "route:POST /returns/:toolId"
      },
      {
        "claims": [],
        "id": "node_c2848c3c55e77a36",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/plugins/load.ts"
          ],
          "symbols": [
            "DeskPlugin",
            "loadPlugins"
          ]
        },
        "slug": "src-plugins-load-ts",
        "title": "src/plugins/load.ts"
      },
      {
        "claims": [],
        "id": "node_cdb4ee2aea69cc6a",
        "kind": "system",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "README.md",
            "package.json",
            "tsconfig.json"
          ]
        },
        "slug": "repository",
        "title": "lending-desk"
      },
      {
        "claims": [],
        "id": "node_db5e0f14edd7dda6",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/notify/reminders.ts"
          ]
        },
        "slug": "src-notify",
        "title": "src/notify"
      },
      {
        "claims": [],
        "id": "node_dd54919d93b38f7b",
        "kind": "module",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "src/catalog/inventory.ts"
          ]
        },
        "slug": "src-catalog",
        "title": "src/catalog"
      },
      {
        "claims": [
          {
            "confidence": 1,
            "evidence": [
              {
                "analyzer": "data",
                "analyzer_version": "0.1.0",
                "blob_hash": "sha256:2aeebecb58cfa527716fd3d3c17998e68167a606d76df8c4866c3ee04e8c0791",
                "commit": "5d5c494696d2875394da0a66958718f34de2fbd4",
                "extract_hash": "sha256:b373c2c9eb935662c469cb6eb3e2ff4116e98c1fef2b2fe39ef16bdb71b0ec82",
                "path": "tsconfig.json",
                "repository": "local"
              }
            ],
            "id": "claim_185759f8abb5fab9",
            "provenance": {
              "actor": "analyzer",
              "created_at": "1970-01-01T00:00:00Z"
            },
            "status": "active",
            "text": "Top-level keys (sorted, max 20): compilerOptions, include.",
            "type": "fact"
          }
        ],
        "id": "node_dde380120d7ca961",
        "kind": "store",
        "relations": [],
        "schema_version": 1,
        "scope": {
          "files": [
            "tsconfig.json"
          ]
        },
        "slug": "tsconfig-json",
        "title": "tsconfig.json"
      }
    ]
  }
};
